# 2. Basic indexing and slicing

Now that we know how to create NumPy arrays, let's see how we can access its elements.

First, we need to import numpy to use it in this notebook.

In [1]:
import numpy as np

## One-dimensional arrays

One-dimensional NumPy arrays can be accessed as a Python list: using `[]``.

In [2]:
my_array = np.arange(1, 13)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

The indexing starts at `0`. The first element is `my_array[0]`, the second `my_array[1]`, ...
You can also start the indexing from the end with negative integers: the last element is `[-1]`, the penultimate is `[-2]`` and so on.

In [3]:
print("first element", my_array[0])
print("second element", my_array[1])
print("last element", my_array[-1])

first element 1
second element 2
last element 12


## Slices
NumPy arrays also support slicing, like Python lists: you can use two values separated by `: ` to get a slice of the array.

In [4]:
my_array[2:5]

array([3, 4, 5])

The indexes are zero-based, the first element is included, and the last one excluded. Don't worry if that seems a bit confusing, it does requires some practice to get used to it!

A famous joke amongst programmers is that the two hardest things to get right in programming are timezones, cache invalidation, and off-by-one errors!

The first index of a slice can be omitted if it's zero, and the last one if you want to go to the end of the array.

In [5]:
# get the first 3 elements
my_array[:3]

array([1, 2, 3])

In [6]:
# get the last 10
my_array[-10:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Slices can also have an increment larger than one: `first_element_included:last_element_excluded:step`.

In [7]:
# get one element out of two, between the second and the tenth elements (both included)
my_array[1:11:2]

array([ 2,  4,  6,  8, 10])

Bounds can also be omitted if you want to take the whole array.

In [8]:
# get one element every third, for the whole array

In [9]:
my_array[::3]

array([ 1,  4,  7, 10])

## Assigning new values
It is possible to assign a new value to any element of an array. The assigned value will be converted to the `dtype` of the array, so ensure it's compatible.

In [10]:
print(my_array)
my_array[3] = 9
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  9  5  6  7  8  9 10 11 12]


In [11]:
print(my_array)
my_array[5] = 4.5
print(my_array)

[ 1  2  3  9  5  6  7  8  9 10 11 12]
[ 1  2  3  9  5  4  7  8  9 10 11 12]


In particular, you might get unexpected behaviours due to integer overflow. Recent versions of NumPy now check for that.

In [12]:
uint_array = np.zeros(3, dtype=np.uint8)
print(uint_array)
uint_array[2] = -1
print(uint_array)

[0 0 0]
[  0   0 255]


/var/folders/hs/9wxtjrjx2k718tlbtzyfl1dm0000gp/T/ipykernel_50412/3112477816.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  uint_array[2] = -1


On the other hand, you can use this behaviour to your advantage if you use boolean arrays, given that in Python, all non-zero values evaluate to `True`. We will use this "trick" later on.

In [13]:
bool_array = np.zeros(4, dtype=bool)
print(bool_array)
bool_array[0] = 12 / 3
print(bool_array)

[False False False False]
[ True False False False]


It is also possible to assign several values at the same time.

In [14]:
my_array = np.arange(1, 13)
print(my_array)
my_array[2:8] = 42
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2 42 42 42 42 42 42  9 10 11 12]


In [15]:
my_array = np.arange(1, 13)
print(my_array)
my_array[4:8] = np.arange(8, 4, -1)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  8  7  6  5  9 10 11 12]


## Multi-dimensional arrays

For arrays with more than one dimension, you can use the same way of indexing for each dimension; each dimension is separated by a `,`.

In [16]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
my_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# get the second element of the first row
my_array[0, 1]

2

It is also possible to get a whole dimension (row or column). `:` can be used as a placeholder to get all elements in that dimension.
(It's actually a slice where both limits are omitted, hence defaulting to the first and the last element!)

In [18]:
# get the first row
my_array[0]

array([1, 2, 3, 4])

In [19]:
# get the column (second dimension)
my_array[:, 0]

array([1, 5, 9])

In [20]:
# get the first and the third line of the last column
my_array[[0, 2], -1]

array([ 4, 12])

You can also assign values.

In [21]:
print(my_array)
my_array[1, 2] = 42
print(my_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6 42  8]
 [ 9 10 11 12]]


## Exercise

Create a 3 x 4 array full of 2, except the top right corner which should contain a 3.

There are several ways of doing that.

In [22]:
# uncomment the following line if you want to load the solution
# %load ../solutions/exercise1.py